name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install forge-std
        run: forge install foundry-rs/forge-std

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: lcov libdatetime-perl

      - name: Run Forge coverage
        run: |
          npm run coverage
        id: coverage

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/index.html
          token: ${{ secrets.CODECOV_TOKEN }}
